{
 "title": "NETOLOGY",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Free Memory (Mb)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes /1048576"
    }
   ]
  },
  {
   "title": "CPU LA",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" },
    { "expr": "node_load5" },
    { "expr": "node_load15" }
   ]
  },
  {
   "title": "Free Space sda2 (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!='tmpfs'} / node_filesystem_size_bytes * 100"
    }
   ]
  }
 ]
}